name: blog
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^12.0.0
  flutter_bloc:
  image_picker: ^1.0.4
  flutter_highlighting: ^0.9.0+11.8.0
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  flutter_svg: ^2.0.10+1
  flutter_dropzone: ^3.0.7
  webviewx:
  connectivity_plus: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
